//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServicingManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BookingService
    {
        public int BookingId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> DeliveryBoyId { get; set; }
        public Nullable<double> TotalCost { get; set; }
        [Required(ErrorMessage = "Vehicle No is required !")]
        public string VehicleNo { get; set; }
        [Required(ErrorMessage = "Service start date is required !")]
        [DataType(DataType.Date)]
        public Nullable<DateTime> ServiceStartDate { get; set; }
        [Required(ErrorMessage = "Service end date is required !")]
        [DataType(DataType.Date)]
        public Nullable<DateTime> ServiceEndDate { get; set; }
        public Nullable<System.DateTime> BookedDate { get; set; }
        public Nullable<int> ServiceCenterId { get; set; }
        public string Status { get; set; }

        public virtual DeliveryBoy DeliveryBoy { get; set; }
        public virtual ServiceCenter ServiceCenter { get; set; }
        public virtual User User { get; set; }
    }
}
