//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryBoysWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryBoy
    {
        public int DeliveryBoyId { get; set; }
        public string Name { get; set; }
        public string Experience { get; set; }
        public Nullable<int> ServiceCenterId { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Mobile { get; set; }
        public string Address { get; set; }
    }
}
